using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using NetOidc.Provider.Configuration;

namespace NetOidc.Provider.Jose;

/// <summary>
/// The provider's view of its keys (from <see cref="IKeyStore"/>): which key signs for a given
/// algorithm, which keys verify and decrypt, and what goes in the JWKS.
/// </summary>
internal sealed class KeyRing
{
    /// <summary>Signing algorithms the provider supports.</summary>
    public static readonly IReadOnlySet<string> SupportedSigningAlgorithms = new HashSet<string>(StringComparer.Ordinal)
    {
        "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384", "ES512",
    };

    /// <summary>
    /// Key-management algorithms for JWE, in both directions (request objects encrypted to the
    /// provider; ID tokens and UserInfo encrypted to clients). Microsoft.IdentityModel supports
    /// neither RSA-OAEP-256 nor ECDH-ES; RSA1_5 is deliberately excluded (RFC 8725 §3.2).
    /// </summary>
    public static readonly IReadOnlySet<string> SupportedEncryptionAlgorithms = new HashSet<string>(StringComparer.Ordinal)
    {
        "RSA-OAEP",
    };

    /// <summary>
    /// Content-encryption algorithms (<c>enc</c>) the provider can produce. Microsoft.IdentityModel
    /// encrypts with AES-CBC-HMAC only; AES-GCM is supported for decryption, not encryption.
    /// </summary>
    public static readonly IReadOnlySet<string> SupportedContentEncryptionAlgorithms = new HashSet<string>(StringComparer.Ordinal)
    {
        "A128CBC-HS256", "A192CBC-HS384", "A256CBC-HS512",
    };

    /// <summary>Content-encryption algorithms accepted in request objects encrypted to the provider.</summary>
    public static readonly IReadOnlySet<string> SupportedContentDecryptionAlgorithms = new HashSet<string>(StringComparer.Ordinal)
    {
        "A128CBC-HS256", "A192CBC-HS384", "A256CBC-HS512", "A128GCM", "A256GCM",
    };

    private readonly IKeyStore _store;
    private readonly IOptions<ProviderOptions> _options;

    public KeyRing(IKeyStore store, IOptions<ProviderOptions> options)
    {
        _store = store;
        _options = options;
    }

    /// <summary>True when any key was generated by the provider rather than configured.</summary>
    public bool HasGeneratedKeys => _store.GetKeys().Any(k => k.IsGenerated);

    /// <summary>Algorithms of the currently active signing keys.</summary>
    public IReadOnlyList<string> SigningAlgorithms =>
        ActiveSigningKeys().Select(k => k.Algorithm).Distinct(StringComparer.Ordinal).ToList();

    /// <summary>
    /// Credentials for the newest active signing key with <paramref name="algorithm"/>, or the
    /// default algorithm (<see cref="ProviderOptions.DefaultSigningAlgorithm"/>, falling back to
    /// any active key) when <c>null</c>.
    /// </summary>
    /// <exception cref="InvalidOperationException">No active key can sign with the algorithm.</exception>
    public SigningCredentials GetSigningCredentials(string? algorithm = null)
    {
        var active = ActiveSigningKeys();
        var wanted = algorithm ?? _options.Value.DefaultSigningAlgorithm;
        var key = active.Where(k => k.Algorithm == wanted).OrderByDescending(k => k.NotBefore ?? DateTimeOffset.MinValue).FirstOrDefault()
                  ?? (algorithm is null ? active.OrderByDescending(k => k.NotBefore ?? DateTimeOffset.MinValue).FirstOrDefault() : null)
                  ?? throw new InvalidOperationException($"No active signing key for algorithm '{wanted}'.");

        return new SigningCredentials(WithKeyId(key), key.Algorithm);
    }

    /// <summary>True when an active signing key supports <paramref name="algorithm"/>.</summary>
    public bool CanSignWith(string algorithm) => ActiveSigningKeys().Any(k => k.Algorithm == algorithm);

    /// <summary>All published signing keys: tokens signed by any of them still verify.</summary>
    public IReadOnlyList<SecurityKey> GetValidationKeys() =>
        PublishedKeys(ProviderKeyUse.Signing).Select(WithKeyId).ToList();

    /// <summary>Key-management algorithms of the published encryption keys.</summary>
    public IReadOnlyList<string> EncryptionAlgorithms =>
        PublishedKeys(ProviderKeyUse.Encryption).Select(k => k.Algorithm).Distinct(StringComparer.Ordinal).ToList();

    /// <summary>All published encryption keys (so requests encrypted to a retiring key still decrypt).</summary>
    public IReadOnlyList<SecurityKey> GetDecryptionKeys() =>
        PublishedKeys(ProviderKeyUse.Encryption).Select(WithKeyId).ToList();

    /// <summary>Public JWKs of every published signing and encryption key, for the JWKS endpoint.</summary>
    public IReadOnlyList<Dictionary<string, object>> GetPublicJwks() =>
        _store.GetKeys()
            .Where(k => k.Use != ProviderKeyUse.Federation && k.IsPublished(DateTimeOffset.UtcNow))
            .Select(ToPublicJwk).ToList();

    /// <summary>Public JWKs of the federation entity keys (published in the entity configuration).</summary>
    public IReadOnlyList<Dictionary<string, object>> GetFederationPublicJwks() =>
        PublishedKeys(ProviderKeyUse.Federation).Select(ToPublicJwk).ToList();

    /// <summary>Credentials of the newest active federation entity key.</summary>
    /// <exception cref="InvalidOperationException">No federation key is active.</exception>
    public SigningCredentials GetFederationSigningCredentials()
    {
        var now = DateTimeOffset.UtcNow;
        var key = _store.GetKeys()
                      .Where(k => k.Use == ProviderKeyUse.Federation && k.IsActive(now))
                      .OrderByDescending(k => k.NotBefore ?? DateTimeOffset.MinValue)
                      .FirstOrDefault()
                  ?? throw new InvalidOperationException("No active federation entity key.");
        return new SigningCredentials(WithKeyId(key), key.Algorithm);
    }

    private List<ProviderKey> ActiveSigningKeys()
    {
        var now = DateTimeOffset.UtcNow;
        return _store.GetKeys().Where(k => k.Use == ProviderKeyUse.Signing && k.IsActive(now)).ToList();
    }

    private IEnumerable<ProviderKey> PublishedKeys(ProviderKeyUse use)
    {
        var now = DateTimeOffset.UtcNow;
        return _store.GetKeys().Where(k => k.Use == use && k.IsPublished(now));
    }

    private static SecurityKey WithKeyId(ProviderKey k)
    {
        if (string.IsNullOrEmpty(k.Key.KeyId)) k.Key.KeyId = k.KeyId;
        return k.Key;
    }

    /// <summary>Builds the public JWK (never private members) for <paramref name="key"/>.</summary>
    internal static Dictionary<string, object> ToPublicJwk(ProviderKey key)
    {
        var jwk = new Dictionary<string, object>(StringComparer.Ordinal)
        {
            ["kid"] = key.KeyId,
            ["use"] = key.Use == ProviderKeyUse.Encryption ? "enc" : "sig",
            ["alg"] = key.Algorithm,
        };

        if (key.PublicJwk is { } published)
        {
            CopyPublic(published, jwk);
            return jwk;
        }

        switch (key.Key)
        {
            case X509SecurityKey x509:
                AddPublic(x509.Certificate.GetRSAPublicKey(), x509.Certificate.GetECDsaPublicKey(), jwk);
                jwk["x5c"] = new[] { Convert.ToBase64String(x509.Certificate.RawData) };
                jwk["x5t#S256"] = Base64UrlEncoder.Encode(x509.Certificate.GetCertHash(HashAlgorithmName.SHA256));
                break;
            case RsaSecurityKey rsa:
                AddRsa(rsa.Rsa?.ExportParameters(false) ?? PublicOnly(rsa.Parameters), jwk);
                break;
            case ECDsaSecurityKey ec:
                AddEc(ec.ECDsa.ExportParameters(false), jwk);
                break;
            case JsonWebKey json:
                CopyPublic(json, jwk);
                break;
            default:
                throw new InvalidOperationException(
                    $"Key '{key.KeyId}' of type {key.Key.GetType().Name} needs an explicit PublicJwk.");
        }
        return jwk;
    }

    private static void AddPublic(RSA? rsa, ECDsa? ec, Dictionary<string, object> jwk)
    {
        using (rsa) using (ec)
        {
            if (rsa is not null) AddRsa(rsa.ExportParameters(false), jwk);
            else if (ec is not null) AddEc(ec.ExportParameters(false), jwk);
            else throw new InvalidOperationException("Certificate key must be RSA or EC.");
        }
    }

    private static RSAParameters PublicOnly(RSAParameters p) => new() { Modulus = p.Modulus, Exponent = p.Exponent };

    private static void AddRsa(RSAParameters p, Dictionary<string, object> jwk)
    {
        jwk["kty"] = "RSA";
        jwk["n"] = Base64UrlEncoder.Encode(p.Modulus!);
        jwk["e"] = Base64UrlEncoder.Encode(p.Exponent!);
    }

    private static void AddEc(ECParameters p, Dictionary<string, object> jwk)
    {
        jwk["kty"] = "EC";
        jwk["crv"] = p.Curve.Oid.FriendlyName switch
        {
            "nistP256" or "ECDSA_P256" => "P-256",
            "nistP384" or "ECDSA_P384" => "P-384",
            "nistP521" or "ECDSA_P521" => "P-521",
            var other => throw new InvalidOperationException($"Unsupported EC curve '{other}'."),
        };
        jwk["x"] = Base64UrlEncoder.Encode(p.Q.X!);
        jwk["y"] = Base64UrlEncoder.Encode(p.Q.Y!);
    }

    private static void CopyPublic(JsonWebKey source, Dictionary<string, object> jwk)
    {
        jwk["kty"] = source.Kty;
        if (source.Kty == "RSA")
        {
            jwk["n"] = source.N;
            jwk["e"] = source.E;
        }
        else if (source.Kty == "EC")
        {
            jwk["crv"] = source.Crv;
            jwk["x"] = source.X;
            jwk["y"] = source.Y;
        }
        if (source.X5c.Count > 0) jwk["x5c"] = source.X5c.ToArray();
    }

    /// <summary>
    /// Hash for <c>at_hash</c>/<c>c_hash</c>/<c>rt_hash</c> (OIDC Core §3.1.3.6): the hash
    /// function of the signing algorithm (SHA-256/384/512).
    /// </summary>
    public static byte[] HashFor(string algorithm, byte[] data) => algorithm[^3..] switch
    {
        "384" => SHA384.HashData(data),
        "512" => SHA512.HashData(data),
        _ => SHA256.HashData(data),
    };
}
